# Viper Cluster Configuration
cluster_name: viper

# Resource defaults
default_partition: general
tasks_per_node: 128
max_nodes: 1592

# SLURM configuration/ limits
slurm:
  # Limits
  time_limit: "24:00:00"
  max_parallel_jobs: 500
